fix cpu buil
open-ce/torchtext-feedstock pull request #22
Opened 2021-07-08 19:30 UTC by cdeepali

## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

2021-07-08 20:24 UTC, jayfurmanek approved these changes

2021-07-09 15:35 UTC, bnemanich requested changes
I think this will make it so torchtext can only be installed with the CPU version of pytorch.

2021-07-09 16:48 UTC, cdeepali commented
No it works with CUDA version too, because we are not adding a run time dependency on `pytorch-select` package hence it works with both CUDA/CPU pytorch-base.

Similar implementation is seen in https://github.com/pytorch/text/commit/f1c7f7d8ab1b6b0643fccce3da58c41db37664de

2021-07-12 17:03 UTC, cdeepali commented
Closing the PR as this change is not needed.

2021-07-12 17:03 UTC, closed without merging